custom_entities:
    supplier:
        entity_class: Acme\Bundle\CatalogBundle\Entity\Supplier
        actions:
            edit:
                form_type: acme_enrich_supplier
            create:
                form_type: acme_enrich_supplier

