services:
    acme_enrich.mass_edit.capitalize_values.processor:
        class: Acme\Bundle\EnrichBundle\Processor\MassEdit\CapitalizeValuesProcessor
        arguments:
            - '@pim_enrich.repository.mass_edit'
            - '@pim_catalog.updater.product'
            - '@pim_validator'
