.. _BatchBundle: https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Tool/Bundle/BatchBundle
.. _ClassificationBundle: https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Tool/Bundle/ClassificationBundle
.. _FileStorageBundle: https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Tool/Bundle/FileStorageBundle
.. _MeasureBundle: https://github.com/akeneo/MeasureBundle
.. _StorageUtilsBundle: https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Tool/Bundle/StorageUtilsBundle

+-------------------------+--------------------------------------------------------------------------------------------------------------------+
| **Bundle**              | **Scope**                                                                                                          |
+-------------------------+--------------------------------------------------------------------------------------------------------------------+
| `BatchBundle`_          | (introduced v1.0) Doctrine and Symfony implementations for the Batch component                                     |
+-------------------------+--------------------------------------------------------------------------------------------------------------------+
| `ClassificationBundle`_ | (introduced v1.4) Doctrine generic implementations for classification trees                                        |
+-------------------------+--------------------------------------------------------------------------------------------------------------------+
| `FileStorageBundle`_    | (introduced v1.4) Doctrine and Symfony implementations for files storage                                           |
+-------------------------+--------------------------------------------------------------------------------------------------------------------+
| `MeasureBundle`_        | (introduced v1.0) Symfony bundle to provide measure families, units and conversion capabilities                    |
+-------------------------+--------------------------------------------------------------------------------------------------------------------+
| `StorageUtilsBundle`_   | (introduced v1.3) Default doctrine implementations for storage access (remover, saver, updater, repositories, etc) |
+-------------------------+--------------------------------------------------------------------------------------------------------------------+
