.. _BatchBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Akeneo/Bundle/BatchBundle
.. _FileStorageBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Akeneo/Bundle/FileStorageBundle
.. _MeasureBundle: https://github.com/akeneo/MeasureBundle
.. _StorageUtilsBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Akeneo/Bundle/StorageUtilsBundle

* `BatchBundle`_
* `FileStorageBundle`_
* `MeasureBundle`_
* `StorageUtilsBundle`_
