.. _BatchBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Akeneo/Bundle/BatchBundle
.. _ClassificationBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Akeneo/Bundle/ClassificationBundle
.. _FileStorageBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Akeneo/Bundle/FileStorageBundle
.. _MeasureBundle: https://github.com/akeneo/MeasureBundle
.. _StorageUtilsBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Akeneo/Bundle/StorageUtilsBundle

+-------------------------+--------------------------------------------------------------------------------------------------+
| **Bundle**              | **Scope**                                                                                        |
+-------------------------+--------------------------------------------------------------------------------------------------+
| `BatchBundle`_          | Doctrine and Symfony implementations for the Batch component                                     |
+-------------------------+--------------------------------------------------------------------------------------------------+
| `ClassificationBundle`_ | Doctrine generic implementations for classification trees                                        |
+-------------------------+--------------------------------------------------------------------------------------------------+
| `FileStorageBundle`_    | Doctrine and Symfony implementations for files storage                                           |
+-------------------------+--------------------------------------------------------------------------------------------------+
| `MeasureBundle`_        | Symfony bundle to provide measure families, units and conversion capabilities                    |
+-------------------------+--------------------------------------------------------------------------------------------------+
| `StorageUtilsBundle`_   | Default doctrine implementations for storage access (remover, saver, updater, repositories, etc) |
+-------------------------+--------------------------------------------------------------------------------------------------+
