.. _AnalyticsBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/AnalyticsBundle
.. _BaseConnectorBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/BaseConnectorBundle
.. _CatalogBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/CatalogBundle
.. _CommentBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/CommentBundle
.. _ConnectorBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/ConnectorBundle
.. _DashboardBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/DashboardBundle
.. _DataGridBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/DataGridBundle
.. _EnrichBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/EnrichBundle
.. _FilterBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/FilterBundle
.. _ImportExportBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/ImportExportBundle
.. _InstallerBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/InstallerBundle
.. _JsFormValidationBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/JsFormValidationBundle
.. _LocalizationBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/LocalizationBundle
.. _NavigationBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/NavigationBundle
.. _NotificationBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/NotificationBundle
.. _PdfGeneratorBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/PdfGeneratorBundle
.. _ReferenceDataBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/ReferenceDataBundle
.. _TransformBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/TransformBundle
.. _UIBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/UIBundle
.. _UserBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/UserBundle
.. _VersioningBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/VersioningBundle
.. _WebServiceBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/WebServiceBundle

+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| **Bundle**                | **Scope**                                                                                                          |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `AnalyticsBundle`_        | (introduced v1.5) Implementations of data collectors to provide PIM statistics                                     |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `BaseConnectorBundle`_    | (introduced v1.0) Legacy import system and still in use export system (will be removed)                            |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `CatalogBundle`_          | (introduced v1.0) PIM business classes (models, model updaters, storage access, validation, etc)                   |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `CommentBundle`_          | (introduced v1.3) Generic comment implementations, used by products                                                |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `ConnectorBundle`_        | (introduced v1.4) classes to integrate import system with Symfony and Doctrine                                     |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `DashboardBundle`_        | (introduced v1.0) Dashboard and widgets system                                                                     |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `DataGridBundle`_         | (introduced v1.0) Override the OroDataGridBundle to add the multi storage capability and product oriented services |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `EnrichBundle`_           | (introduced v1.0) Symfony and Doctrine glue classes to provide User Interface                                      |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `FilterBundle`_           | (introduced v1.0) Override the OroFilterBundle to add the multi storage capability and product oriented services   |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `ImportExportBundle`_     | (introduced v1.0) UI for import/export                                                                             |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `InstallerBundle`_        | (introduced v1.0) Installation system of the PIM                                                                   |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `JsFormValidationBundle`_ | (introduced v1.0) Override of APY/JsFormValidationBundle to provide javascript validation for dynamic models       |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `LocalizationBundle`_     | (introduced v1.5) Symfony implementation of localization features                                                  |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `NavigationBundle`_       | (introduced v1.0) Override OroNavigationBundle                                                                     |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `NotificationBundle`_     | (introduced v1.3) Implementation of a centralized PIM notifications system                                         |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `PdfGeneratorBundle`_     | (introduced v1.3) Classes to generate a PDF datasheet for a product                                                |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `ReferenceDataBundle`_    | (introduced v1.4) Classes to provide reference data support for PIM features                                       |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `TransformBundle`_        | (introduced v1.0) Handles normalization and denormalization of PIM models                                          |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `UIBundle`_               | (introduced v1.0) CSS and JS Assets for the PIM                                                                    |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `UserBundle`_             | (introduced v1.0) Override OroUserBundle                                                                           |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `VersioningBundle`_       | (introduced v1.0) Versioning implementation for the PIM domain models                                              |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
| `WebServiceBundle`_       | (introduced v1.0) Very light Web Rest API (json format)                                                            |
+---------------------------+--------------------------------------------------------------------------------------------------------------------+
