.. _AnalyticsBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/AnalyticsBundle
.. _BaseConnectorBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/BaseConnectorBundle
.. _CatalogBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/CatalogBundle
.. _CommentBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/CommentBundle
.. _ConnectorBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/ConnectorBundle
.. _DashboardBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/DashboardBundle
.. _DataGridBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/DataGridBundle
.. _EnrichBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/EnrichBundle
.. _FilterBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/FilterBundle
.. _ImportExportBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/ImportExportBundle
.. _InstallerBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/InstallerBundle
.. _JsFormValidationBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/JsFormValidationBundle
.. _LocalizationBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/LocalizationBundle
.. _NavigationBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/NavigationBundle
.. _NotificationBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/NotificationBundle
.. _PdfGeneratorBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/PdfGeneratorBundle
.. _ReferenceDataBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/ReferenceDataBundle
.. _TransformBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/TransformBundle
.. _UIBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/UIBundle
.. _UserBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/UserBundle
.. _VersioningBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/VersioningBundle
.. _WebServiceBundle: https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/WebServiceBundle

+---------------------------+--------------------------------------------------------------------------------------------------+
| **Bundle**                | **Scope**                                                                                        |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `AnalyticsBundle`_        | Implementations of data collectors to provide PIM statistics                                     |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `BaseConnectorBundle`_    | Legacy import system and still in use export system (will be removed)                            |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `CatalogBundle`_          | PIM business classes (models, model updaters, storage access, validation, etc)                   |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `CommentBundle`_          | Generic comment implementations, used by products                                                |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `ConnectorBundle`_        | New (introduced in v1.4) classes to integrate import system with Symfony and Doctrine            |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `DashboardBundle`_        | Dashboard and widgets system                                                                     |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `DataGridBundle`_         | Override the OroDataGridBundle to add the multi storage capability and product oriented services |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `EnrichBundle`_           | Symfony and Doctrine glue classes to provide User Interface                                      |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `FilterBundle`_           | Override the OroFilterBundle to add the multi storage capability and product oriented services   |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `ImportExportBundle`_     | UI for import/export                                                                             |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `InstallerBundle`_        | Installation system of the PIM                                                                   |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `JsFormValidationBundle`_ | Override of APY/JsFormValidationBundle to provide javascript validation for dynamic models       |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `LocalizationBundle`_     | Symfony implementation of localization features                                                  |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `NavigationBundle`_       | Override OroNavigationBundle                                                                     |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `NotificationBundle`_     | Implementation of a centralized PIM notifications system                                         |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `PdfGeneratorBundle`_     | Classes to generate a PDF datasheet for a product                                                |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `ReferenceDataBundle`_    | Classes to provide reference data support for PIM features                                       |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `TransformBundle`_        | Handles normalization and denormalization of PIM models                                          |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `UIBundle`_               | CSS and JS Assets for the PIM                                                                    |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `UserBundle`_             | Override OroUserBundle                                                                           |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `VersioningBundle`_       | Versioning implementation for the PIM domain models                                              |
+---------------------------+--------------------------------------------------------------------------------------------------+
| `WebServiceBundle`_       | Very light Web Rest API (json format)                                                            |
+---------------------------+--------------------------------------------------------------------------------------------------+
