.. _Analytics: https://github.com/akeneo/pim-community-dev/tree/v2.3.0/src/Akeneo/Component/Analytics
.. _Batch: https://github.com/akeneo/pim-community-dev/tree/v2.3.0/src/Akeneo/Component/Batch
.. _Buffer: https://github.com/akeneo/pim-community-dev/tree/v2.3.0/src/Akeneo/Component/Buffer
.. _Classification: https://github.com/akeneo/pim-community-dev/tree/v2.3.0/src/Akeneo/Component/Classification
.. _Console: https://github.com/akeneo/pim-community-dev/tree/v2.3.0/src/Akeneo/Component/Console
.. _FileStorage: https://github.com/akeneo/pim-community-dev/tree/v2.3.0/src/Akeneo/Component/FileStorage
.. _Localization: https://github.com/akeneo/pim-community-dev/tree/v2.3.0/src/Akeneo/Component/Localization
.. _StorageUtils: https://github.com/akeneo/pim-community-dev/tree/v2.3.0/src/Akeneo/Component/StorageUtils
.. _Versioning: https://github.com/akeneo/pim-community-dev/tree/v2.3.0/src/Akeneo/Component/Versioning

+-------------------+------------------------------------------------------------------------------------------------------------------------------+
| **Component**     | **Scope**                                                                                                                    |
+-------------------+------------------------------------------------------------------------------------------------------------------------------+
| `Analytics`_      | (introduced v1.4) Data collector interfaces to aggregate statistics                                                          |
+-------------------+------------------------------------------------------------------------------------------------------------------------------+
| `Batch`_          | (introduced v1.5) Batch domain interfaces and classes (extracted from previous BatchBundle version)                          |
+-------------------+------------------------------------------------------------------------------------------------------------------------------+
| `Buffer`_         | (introduced v1.5) Buffer domain interfaces and classes (extracted from previous BatchBundle version)                         |
+-------------------+------------------------------------------------------------------------------------------------------------------------------+
| `Classification`_ | (introduced v1.4) Generic classes for classification trees (implemented by product categories and asset categories) and tags |
+-------------------+------------------------------------------------------------------------------------------------------------------------------+
| `Console`_        | (introduced v1.4) Utility classes to execute commands                                                                        |
+-------------------+------------------------------------------------------------------------------------------------------------------------------+
| `FileStorage`_    | (introduced v1.4) Business interfaces and classes to handle files storage with filesystem abstraction                        |
+-------------------+------------------------------------------------------------------------------------------------------------------------------+
| `Localization`_   | (introduced v1.5) Localization domain interfaces and classes                                                                 |
+-------------------+------------------------------------------------------------------------------------------------------------------------------+
| `StorageUtils`_   | (introduced v1.3) Business interfaces and classes to abstract storage access (remover, saver, updater, repositories, etc)    |
+-------------------+------------------------------------------------------------------------------------------------------------------------------+
| `Versioning`_     | (introduced v1.5) Versioning domain interfaces and classes                                                                   |
+-------------------+------------------------------------------------------------------------------------------------------------------------------+
