.. _Connector: https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Component/Connector
.. _Catalog: https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Component/Catalog
.. _ReferenceData: https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Component/ReferenceData

+------------------+--------------------------------------------------------------------------------------------------------------------+
| **Component**    | **Scope**                                                                                                          |
+------------------+--------------------------------------------------------------------------------------------------------------------+
| `Catalog`_       | (introduced v1.4) PIM domain interfaces and classes, most of them still remain in CatalogBundle for legacy reasons |
+------------------+--------------------------------------------------------------------------------------------------------------------+
| `Connector`_     | (introduced v1.4) PIM business interfaces and classes to handle data import                                        |
+------------------+--------------------------------------------------------------------------------------------------------------------+
| `ReferenceData`_ | (introduced v1.4) Interfaces and classes related to collection of reference models and the product integration     |
+------------------+--------------------------------------------------------------------------------------------------------------------+
