Acme\Bundle\CatalogBundle\Entity\Supplier:
    type: entity
    table: acme_catalog_supplier
    repositoryClass: Pim\Bundle\CustomEntityBundle\Entity\Repository\TranslatableCustomOptionRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 100
            unique: true
        name:
            type: string
            length: 255
        phone:
            type: string
            length: 255
        email:
            type: string
            length: 255
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        translations:
            targetEntity: Acme\Bundle\CatalogBundle\Entity\SupplierTranslation
            mappedBy: foreignKey
            cascade:
                - persist
