* Setup data
    * :doc:`/cookbook/setup_data/customize_installer`

* Manipulate product
    * :doc:`/cookbook/product/manipulate-product`
    * :doc:`/cookbook/product/query-products`

* Import / export
    * :doc:`/cookbook/import_export/create-connector`
    * :doc:`/cookbook/import_export/create-specific-connector`
    * :doc:`/cookbook/import_export/create-custom-step`
    * :doc:`/cookbook/import_export/customize-import-behavior`
    * :doc:`/cookbook/import_export/mongodb-fast-writer`

* Creating custom entities
    * :doc:`/cookbook/custom_entity/index`

* Form customization
    * :doc:`/cookbook/form_customization/add_a_new_tab_to_product_edit_form`

* Mass edition
    * :doc:`/cookbook/mass_edition/register_a_new_mass_edit_action`

* Updaters
    * :doc:`/cookbook/updaters/product-updater`

* Validation
    * :doc:`/cookbook/validation/customize_validation`

* Access Control List
    * :doc:`/cookbook/acl/define-acl`

* Categories
    * :doc:`/cookbook/category/add-properties-to-category`

* REST API
    * :doc:`/cookbook/rest_api/get-product`

* Notifications
    * :doc:`/cookbook/notification/how_to_add_a_notification`
