* :doc:`/contributing/contributing`
* `Install development repository`_
* :doc:`/contributing/behat`
* :doc:`/contributing/service_definition`
* `Coding standard`_
* `Code conventions`_
* `License agreement`_

.. _Install development repository: https://github.com/akeneo/pim-community-dev/blob/master/README.md
.. _Coding standard: http://symfony.com/doc/current/contributing/code/standards.html
.. _Code conventions: http://symfony.com/doc/current/contributing/code/conventions.html
.. _License agreement: http://www.akeneo.com/contributor-license-agreement/
