.. _report_bug:

Report a Bug
------------

**Prerequisite**

.. warning::

    As a prerequisite, make sure you completed all the steps described in our :doc:`/troubleshooting/first_aid_kit/index`.

**Community Edition**

* Check if the issue is reproducible on http://demo.akeneo.com
* Check if this issue is already known: https://github.com/akeneo/pim-community-dev/issues
* Clone https://github.com/akeneo/pim-community-dev and checkout the branch of the version you want to test
* Reproduce the bug
* Gather as much information as possible by following our :doc:`/troubleshooting/bug_qualification/index` guide
* Create a new `GitHub <https://github.com/akeneo/pim-community-dev/>`_ issue which:

  * Clearly describes the issue in its title
  * Describes the steps to reproduce the bug
  * Provides the PIM system information available under System > System information
  * Provides as much information as possible on your environment (OS, PHP version, browser)

* Don't hesitate to claim your badge "`Bug Hunter <http://badger.akeneo.com/badge/57861115-69f6-11e6-92dc-d60437e930cf>`_" on `badger <http://badger.akeneo.com/>`_

**Enterprise Edition**

* Gather as much information as possible by following our :doc:`/troubleshooting/bug_qualification/index` guide
* Raise an issue by using your `Service Desk Account <http://helpdesk.akeneo.com/>`_
* Attach the PIM system information file to your request (it is available under System > System information > TXT)
* Our support team will handle your request
