.. _report_bug:

Report a Bug
------------

**Prerequisite**

.. warning::

    As a prerequisite, make sure you completed all the steps described in our :doc:`/maintain_pim/first_aid_kit/index`.

**Community Edition**

* Check if this issue is `already known <https://github.com/akeneo/pim-community-dev/issues>`_
* Clone `the development repository <https://github.com/akeneo/pim-community-dev>`_ and checkout the branch of the version you want to test
* Reproduce the bug
* Gather as much information as possible by following our :doc:`/maintain_pim/bug_qualification/index` guide
* Create a new `GitHub <https://github.com/akeneo/pim-community-dev/>`_ issue which:

  * Clearly describes the issue in its title
  * Describes the steps to reproduce the bug
  * Provides the PIM system information available under System > System information
  * Provides as much information as possible on your environment (OS, PHP version, browser)

**Enterprise Edition**

* Gather as much information as possible by following our :doc:`/maintain_pim/bug_qualification/index` guide
* Raise an issue by using your `Service Desk Account <https://helpdesk.akeneo.com>`_
* Attach the PIM system information file to your request (it is available under System > System information > TXT)
* Submit your request on our Helpdesk
