extensions:
    pim-job-instance-csv-product-export-notify-show:
        module: pim/form/common/edit-form

    pim-job-instance-csv-product-export-notify-show-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-csv-product-export-notify-show
        targetZone: content
        position: 100

    pim-job-instance-csv-product-export-notify-show-properties:
        module: pim/job/common/edit/properties
        parent: pim-job-instance-csv-product-export-notify-show-tabs
        aclResourceId: pim_importexport_export_profile_property_show
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    pim-job-instance-csv-product-export-notify-show-content:
        module: pim/job/product/edit/content
        parent: pim-job-instance-csv-product-export-notify-show-tabs
        aclResourceId: pim_importexport_export_profile_content_show
        targetZone: container
        position: 110
        config:
            tabTitle: pim_enrich.form.job_instance.tab.content.title
            tabCode: pim-job-instance-content

    pim-job-instance-csv-product-export-notify-show-history:
        module: pim/common/tab/history
        parent: pim-job-instance-csv-product-export-notify-show-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Tool\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    pim-job-instance-csv-product-export-notify-show-properties-code:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-export-notify-show-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    pim-job-instance-csv-product-export-notify-show-properties-label:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-export-notify-show-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    pim-job-instance-csv-product-export-notify-show-properties-storage:
        module: pimimportexport/js/job/common/edit/storage-form
        parent: pim-job-instance-csv-product-export-notify-show-properties
        position: 120
        targetZone: additional-properties
        config:
            tabCode: pim-job-instance-properties
            jobType: import
            fileExtension: csv

    pim-job-instance-csv-product-export-notify-show-properties-decimal-separator:
        module: pim/job/common/edit/field/decimal-separator
        parent: pim-job-instance-csv-product-export-notify-show-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.decimalSeparator
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.decimal_separator.title
            tooltip: pim_enrich.form.job_instance.tab.properties.decimal_separator.help

    pim-job-instance-csv-product-export-notify-show-properties-date-format:
        module: pim/job/product/edit/field/date-format
        parent: pim-job-instance-csv-product-export-notify-show-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.dateFormat
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.date_format.title
            tooltip: pim_enrich.form.job_instance.tab.properties.date_format.help

    pim-job-instance-csv-product-export-notify-show-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-export-notify-show-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.delimiter.help

    pim-job-instance-csv-product-export-notify-show-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-export-notify-show-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.enclosure.help

    pim-job-instance-csv-product-export-notify-show-properties-with-header:
        module: pim/job/common/edit/field/switch
        parent: pim-job-instance-csv-product-export-notify-show-properties
        position: 170
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_header.help

    pim-job-instance-csv-product-export-notify-show-properties-with-media:
        module: pim/job/common/edit/field/switch
        parent: pim-job-instance-csv-product-export-notify-show-properties
        position: 180
        targetZone: global-settings
        config:
            fieldCode: configuration.with_media
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.with_media.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_media.help

    pim-job-instance-csv-product-export-notify-show-content-structure:
        module: pim/job/product/edit/content/structure
        parent: pim-job-instance-csv-product-export-notify-show-content
        targetZone: structure-filters
        position: 100

    pim-job-instance-csv-product-export-notify-show-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-csv-product-export-notify-show
        targetZone: title
        position: 100

    pim-job-instance-csv-product-export-notify-show-meta:
        module: pim/job/common/edit/meta
        parent: pim-job-instance-csv-product-export-notify-show
        targetZone: meta
        position: 100

    pim-job-instance-csv-product-export-notify-show-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: pim-job-instance-csv-product-export-notify-show
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    pim-job-instance-csv-product-export-notify-show-content-structure-scope:
        module: pim/job/product/edit/content/structure/scope
        parent: pim-job-instance-csv-product-export-notify-show-content-structure
        targetZone: filters
        position: 90
        config:
            readOnly: true

    pim-job-instance-csv-product-export-notify-show-content-structure-locales:
        module: pim/job/product/edit/content/structure/locales
        parent: pim-job-instance-csv-product-export-notify-show-content-structure
        targetZone: filters
        position: 100
        config:
            readOnly: true

    pim-job-instance-csv-product-export-notify-show-content-structure-attributes:
        module: pim/job/product/edit/content/structure/attributes
        parent: pim-job-instance-csv-product-export-notify-show-content-structure
        targetZone: filters
        position: 110
        config:
            readOnly: true

    pim-job-instance-csv-product-export-notify-show-content-data:
        module: pim/job/product/edit/content/data
        parent: pim-job-instance-csv-product-export-notify-show-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: family
                    view: akeneo-product-family-filter
                -
                    field: enabled
                    view: akeneo-product-enabled-filter
                -
                    field: completeness
                    view: akeneo-product-completeness-filter
                -
                    field: updated
                    view: akeneo-product-updated-filter
                -
                    field: categories
                    view: akeneo-product-category-filter

    pim-job-instance-csv-product-export-notify-show-content-readonly:
        module: pim/job/product/edit/content/readonly
        parent: pim-job-instance-csv-product-export-notify-show-content

    pim-job-instance-csv-product-export-notify-show-content-default-attribute-filters:
        module: pim/job/product/edit/content/data/default-attribute-filters
        parent: pim-job-instance-csv-product-export-notify-show-content-data
        config:
            types: [pim_catalog_identifier]

    pim-job-instance-csv-product-export-notify-show-content-data-help:
        module: pim/job/product/edit/content/data/help
        parent: pim-job-instance-csv-product-export-notify-show-content-data

    pim-job-instance-csv-product-export-notify-show-edit:
        module: pim/common/redirect
        parent: pim-job-instance-csv-product-export-notify-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_export_profile_edit
            identifier:
                path: code
                name: code

    pim-job-instance-csv-product-export-notify-show-launch:
        module: pim/job/common/edit/launch
        parent: pim-job-instance-csv-product-export-notify-show
        targetZone: buttons
        position: 110
        config:
            label: pim_enrich.form.job_instance.button.export.title
            route: pim_enrich_job_instance_rest_export_launch
            identifier:
                path: code
                name: code

    # src/Acme/Bundle/NotifyConnectorBundle/Resources/config/form_extensions/csv_product_export_notify_show.yml
    pim-job-instance-csv-product-export-notify-show-properties-url-to-notify:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-export-notify-show-properties
        position: 190
        targetZone: properties
        config:
            fieldCode: configuration.urlToNotify
            readOnly: true
            label: acme.form.job_instance.tab.properties.url_to_notify.title
