extensions:
    pim-job-instance-csv-product-export-notify-edit:
        module: pim/form/common/edit-form

    pim-job-instance-csv-product-export-notify-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-job-instance-csv-product-export-notify-edit
        position: 1000

    pim-job-instance-csv-product-export-notify-edit-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-csv-product-export-notify-edit
        targetZone: content
        position: 100

    pim-job-instance-csv-product-export-notify-edit-properties:
        module: pim/job/common/edit/properties
        parent: pim-job-instance-csv-product-export-notify-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    pim-job-instance-csv-product-export-notify-notify-edit-content:
        module: pim/job/product/edit/content
        parent: pim-job-instance-csv-product-export-notify-edit-tabs
        aclResourceId: pim_importexport_export_profile_content_edit
        targetZone: container
        position: 110
        config:
            tabTitle: pim_enrich.form.job_instance.tab.content.title
            tabCode: pim-job-instance-content

    pim-job-instance-csv-product-export-notify-edit-history:
        module: pim/common/tab/history
        parent: pim-job-instance-csv-product-export-notify-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Tool\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    pim-job-instance-csv-product-export-notify-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-export-notify-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    pim-job-instance-csv-product-export-notify-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-export-notify-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    pim-job-instance-csv-base-import-edit-properties-storage:
        module: pimimportexport/js/job/common/edit/storage-form
        parent: pim-job-instance-csv-product-export-notify-edit-properties
        position: 120
        targetZone: additional-properties
        config:
            tabCode: pim-job-instance-properties
            jobType: import
            fileExtension: csv

    pim-job-instance-csv-product-export-notify-edit-properties-decimal-separator:
        module: pim/job/common/edit/field/decimal-separator
        parent: pim-job-instance-csv-product-export-notify-edit-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.decimalSeparator
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.decimal_separator.title
            tooltip: pim_enrich.form.job_instance.tab.properties.decimal_separator.help

    pim-job-instance-csv-product-export-notify-edit-properties-date-format:
        module: pim/job/product/edit/field/date-format
        parent: pim-job-instance-csv-product-export-notify-edit-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.dateFormat
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.date_format.title
            tooltip: pim_enrich.form.job_instance.tab.properties.date_format.help

    pim-job-instance-csv-product-export-notify-edit-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-export-notify-edit-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.delimiter.help

    pim-job-instance-csv-product-export-notify-edit-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-export-notify-edit-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.enclosure.help

    pim-job-instance-csv-product-export-notify-edit-properties-with-header:
        module: pim/job/common/edit/field/switch
        parent: pim-job-instance-csv-product-export-notify-edit-properties
        position: 170
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_header.help

    pim-job-instance-csv-product-export-notify-edit-properties-with-media:
        module: pim/job/common/edit/field/switch
        parent: pim-job-instance-csv-product-export-notify-edit-properties
        position: 180
        targetZone: global-settings
        config:
            fieldCode: configuration.with_media
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.with_media.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_media.help

    pim-job-instance-csv-product-export-notify-edit-content-structure:
        module: pim/job/product/edit/content/structure
        parent: pim-job-instance-csv-product-export-notify-edit-content
        targetZone: structure-filters
        position: 100

    pim-job-instance-csv-product-export-notify-edit-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-csv-product-export-notify-edit
        targetZone: title
        position: 100

    pim-job-instance-csv-product-export-notify-edit-meta:
        module: pim/job/common/edit/meta
        parent: pim-job-instance-csv-product-export-notify-edit
        targetZone: meta
        position: 100

    pim-job-instance-csv-product-export-notify-edit-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: pim-job-instance-csv-product-export-notify-edit
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    pim-job-instance-csv-product-export-notify-edit-delete:
        module: pim/job/export/edit/delete
        parent: pim-job-instance-csv-product-export-notify-edit
        targetZone: buttons
        aclResourceId: pim_importexport_export_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.job_instance
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    pim-job-instance-csv-product-export-notify-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-job-instance-csv-product-export-notify-edit
        targetZone: buttons
        position: 120

    pim-job-instance-csv-product-export-notify-edit-save:
        module: pim/job-instance-export-edit-form/save
        parent: pim-job-instance-csv-product-export-notify-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_export_profile_show

    pim-job-instance-csv-product-export-notify-edit-state:
        module: pim/form/common/state
        parent: pim-job-instance-csv-product-export-notify-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title


    pim-job-instance-csv-product-export-notify-edit-content-structure-scope:
        module: pim/job/product/edit/content/structure/scope
        parent: pim-job-instance-csv-product-export-notify-edit-content-structure
        targetZone: filters
        position: 90

    pim-job-instance-csv-product-export-notify-edit-content-structure-locales:
        module: pim/job/product/edit/content/structure/locales
        parent: pim-job-instance-csv-product-export-notify-edit-content-structure
        targetZone: filters
        position: 100

    pim-job-instance-csv-product-export-notify-edit-content-structure-attributes:
        module: pim/job/product/edit/content/structure/attributes
        parent: pim-job-instance-csv-product-export-notify-edit-content-structure
        targetZone: filters
        position: 110

    pim-job-instance-csv-product-export-notify-edit-content-data:
        module: pim/job/product/edit/content/data
        parent: pim-job-instance-csv-product-export-notify-edit-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: family
                    view: akeneo-product-family-filter
                -
                    field: enabled
                    view: akeneo-product-enabled-filter
                -
                    field: completeness
                    view: akeneo-product-completeness-filter
                -
                    field: updated
                    view: akeneo-product-updated-filter
                -
                    field: categories
                    view: akeneo-product-category-filter

    pim-job-instance-csv-product-export-notify-edit-content-default-attribute-filters:
        module: pim/job/product/edit/content/data/default-attribute-filters
        parent: pim-job-instance-csv-product-export-notify-edit-content-data
        config:
            types: [pim_catalog_identifier]

    pim-job-instance-csv-product-export-notify-edit-content-data-help:
        module: pim/job/product/edit/content/data/help
        parent: pim-job-instance-csv-product-export-notify-edit-content-data

    pim-job-instance-csv-product-export-notify-edit-validation:
        module: pim/job/common/edit/validation
        parent: pim-job-instance-csv-product-export-notify-edit

    pim-job-instance-csv-product-export-notify-edit-content-data-add-filter:
        module: pim/job/product/edit/content/data/add-select/attribute
        parent: pim-job-instance-csv-product-export-notify-edit-content-data
        targetZone: headings
        position: 90

    # src/Acme/Bundle/NotifyConnectorBundle/Resources/config/form_extensions/csv_product_export_notify_edit.yml
    pim-job-instance-csv-product-export-notify-edit-properties-url-to-notify:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-export-notify-edit-properties
        position: 190
        targetZone: properties
        config:
            fieldCode: configuration.urlToNotify
            readOnly: false
            label: acme.form.job_instance.tab.properties.url_to_notify.title
            tooltip: acme.form.job_instance.tab.properties.url_to_notify.help
